import fs from 'node:fs';
import path from 'node:path';
import type { HarnessDb } from '../db/HarnessDb.js';
import type { HarnessPaths } from '../paths.js';
import type { DesignRule, HarnessEntry } from '../types.js';

/**
 * The markdown spec is a projection of the database, rewritten after every
 * approved change. It is committable — a reviewer reads the diff of these files
 * in a pull request, while the database keeps working state (pending, checkpoints).
 */
export function writeSpecFiles(db: HarnessDb, paths: HarnessPaths): string[] {
  fs.mkdirSync(paths.tasks, { recursive: true });
  const written: string[] = [];

  write(paths.constitution, constitutionMd(db), written);
  write(paths.structure, structureMd(db), written);
  write(paths.design, designMd(db), written);
  write(paths.spec, specMd(db), written);

  const steps = db.listEntries('step');
  const phases = [...new Set(steps.map((s) => s.phase ?? 1))].sort((a, b) => a - b);
  for (const phase of phases) {
    write(path.join(paths.tasks, `phase-${phase}.md`), phaseMd(steps, phase), written);
  }
  // Phases that lost all their steps must not linger on disk.
  for (const f of fs.existsSync(paths.tasks) ? fs.readdirSync(paths.tasks) : []) {
    const m = /^phase-(\d+)\.md$/.exec(f);
    if (m && !phases.includes(Number(m[1]))) fs.rmSync(path.join(paths.tasks, f));
  }
  return written;
}

function write(file: string, content: string, written: string[]): void {
  const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (prev === content) return;
  fs.writeFileSync(file, content, 'utf8');
  written.push(file);
}

const HEADER = `<!-- Generated by Harness MCP. This file is the harness — the source of truth
     the agent implements from. Do not hand-edit: propose a change through
     harness_propose_change so a human can review the diff. -->`;

function marker(e: HarnessEntry): string {
  return e.confidence === 'assumption' ? ' `[assumption]`' : '';
}

function questionNote(e: HarnessEntry): string {
  return e.question ? `\n  > ❓ ${e.question}\n` : '';
}

export function constitutionMd(db: HarnessDb): string {
  const items = db.listEntries('constitution');
  const decisions = db.listEntries('decision');
  const lines = [HEADER, '', '# Constitution', ''];
  lines.push('> Injected into every agent turn. Invariants here are inviolable.', '');

  if (!items.length) lines.push('_Not assembled yet — run `harness_init` or `harness_reverse`._', '');
  for (const e of items) {
    lines.push(`## ${e.title}${marker(e)}`, '', e.body.trim(), questionNote(e), '');
  }

  lines.push('## Decisions', '');
  if (!decisions.length) lines.push('_None recorded._', '');
  for (const d of decisions) {
    lines.push(`- **${d.title}**${marker(d)} — ${oneLine(d.body)}${d.question ? ` ❓ ${d.question}` : ''}`);
  }
  lines.push('');
  return lines.join('\n');
}

export function structureMd(db: HarnessDb): string {
  const nodes = db.listEntries('structure');
  const lines = [HEADER, '', '# Structure', ''];
  if (!nodes.length) return lines.concat('_Not assembled yet._', '').join('\n');

  const byParent = new Map<string | null, HarnessEntry[]>();
  for (const n of nodes) {
    const parent = (n.data.parent as string | null | undefined) ?? null;
    const bucket = byParent.get(parent) ?? [];
    bucket.push(n);
    byParent.set(parent, bucket);
  }
  // Nodes whose declared parent is missing are still shown, at the root.
  const keys = new Set(nodes.map((n) => n.key));
  for (const [parent, bucket] of byParent) {
    if (parent && !keys.has(parent)) {
      byParent.set(null, [...(byParent.get(null) ?? []), ...bucket]);
      byParent.delete(parent);
    }
  }

  const walk = (parent: string | null, depth: number): void => {
    for (const n of byParent.get(parent) ?? []) {
      const kind = n.data.kind ? `_${n.data.kind}_ ` : '';
      const at = n.data.path ? ` — \`${n.data.path}\`` : '';
      lines.push(`${'  '.repeat(depth)}- ${kind}**${n.title}**${at}${marker(n)}`);
      if (n.body.trim()) lines.push(`${'  '.repeat(depth + 1)}${oneLine(n.body)}`);
      if (n.question) lines.push(`${'  '.repeat(depth + 1)}> ❓ ${n.question}`);
      walk(n.key, depth + 1);
    }
  };
  walk(null, 0);
  lines.push('');
  return lines.join('\n');
}

export function designMd(db: HarnessDb): string {
  const entries = db.listEntries('design');
  const rules = db.listDesignRules();
  const tokens = db.getDesignTokens();
  const lines = [HEADER, '', '# Design', ''];

  if (tokens) {
    lines.push(
      `## Tokens`,
      '',
      `Source: **${tokens.source}** (fetched ${tokens.fetched_at.slice(0, 10)}). Use these, never ad-hoc values.`,
      '',
      `- radius: control \`${tokens.radii.control}\` · card \`${tokens.radii.card}\` · pill \`${tokens.radii.pill}\``,
      `- colour: text \`${tokens.colors.text}\` · muted \`${tokens.colors.muted}\` · surface \`${tokens.colors.surface}\` · border \`${tokens.colors.border}\` · accent \`${tokens.colors.accent}\``,
      `- type: heading \`${tokens.fonts.heading}\` · body \`${tokens.fonts.body}\``,
      `- spacing: \`${tokens.spacing.xs}\` / \`${tokens.spacing.sm}\` / \`${tokens.spacing.md}\``,
      '',
    );
  }

  lines.push('## Global rules', '');
  lines.push('> Every rule below applies to the whole project. The agent must satisfy all of them in any UI it writes.', '');
  if (!rules.length) lines.push('_None yet — add one with `harness_add_design_rule`._', '');
  for (const r of rules) lines.push(`- ${ruleLine(r)}`);
  lines.push('');

  lines.push('## Screens & patterns', '');
  if (!entries.length) lines.push('_None yet._', '');
  for (const e of entries) {
    lines.push(`### ${e.title}${marker(e)}`, '', e.body.trim(), questionNote(e), '');
  }
  return lines.join('\n');
}

function ruleLine(r: DesignRule): string {
  const scope = r.scope === 'global' ? '' : ` _(${r.scope})_`;
  const check = r.check ? ` \`check: ${r.check.glob} ${r.check.forbidden ? '!~' : '~'} /${r.check.pattern}/\`` : '';
  return `${r.rule}${scope}${check}`;
}

export function specMd(db: HarnessDb): string {
  const reqs = db.listEntries('requirement');
  const lines = [HEADER, '', '# Specification', ''];
  lines.push('> EARS notation. Each requirement carries the *why* it was captured with.', '');
  if (!reqs.length) lines.push('_Not assembled yet._', '');
  for (const r of reqs) {
    lines.push(`### ${r.key} — ${r.title}${marker(r)}`, '', r.body.trim(), '');
    const why = r.data.why as string | undefined;
    if (why) lines.push(`_Why:_ ${why}`, '');
    if (r.question) lines.push(`> ❓ ${r.question}`, '');
  }
  return lines.join('\n');
}

export function phaseMd(steps: HarnessEntry[], phase: number): string {
  const mine = steps.filter((s) => (s.phase ?? 1) === phase);
  const lines = [HEADER, '', `# Phase ${phase}`, ''];
  for (const s of mine) {
    lines.push(`## ${s.key} — ${s.title}${marker(s)}`, '');
    if (s.body.trim()) lines.push(s.body.trim(), '');
    const verify = s.data.verify as string | undefined;
    lines.push(`verify: \`${verify ?? 'TODO — declare an executable check'}\``, '');
  }
  return lines.join('\n');
}

const oneLine = (s: string) => s.trim().replace(/\s*\n\s*/g, ' ');
