#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Inlines `src/prompts/**\/*.md` into one generated TypeScript module.
 *
 * The markdown is the source of truth and stays readable in the repository — a
 * prompt change has to show up as a prompt diff, which is the whole reason the
 * text left the code. The generated file is git-ignored so it never doubles those
 * diffs.
 *
 * Inlining rather than reading from disk is forced by how this ships: the editor
 * bundles the server into a single .mjs with esbuild, and loose markdown next to
 * the entry point would simply not travel with it. Verified, not assumed — the
 * bundler is `projectmind-ui/scripts/bundle-harness-mcp.mjs`.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.join(here, '..');
const promptsDir = path.join(repo, 'src', 'prompts');
const outFile = path.join(promptsDir, 'generated.ts');

/** Every .md under src/prompts, keyed by its path without the extension. */
function collect(dir, prefix = '') {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...collect(full, prefix ? `${prefix}/${e.name}` : e.name));
    } else if (e.name.endsWith('.md')) {
      const id = `${prefix}/${e.name.replace(/\.md$/, '')}`;
      // Trailing newlines are an artefact of the file, not of the prompt: the
      // builder decides spacing between sections, so normalise it away here.
      out.push([id, fs.readFileSync(full, 'utf8').replace(/\s+$/, '')]);
    }
  }
  return out;
}

const fragments = collect(promptsDir);
if (!fragments.length) {
  console.error('[prompts] no .md files found under src/prompts — refusing to write an empty module.');
  process.exit(1);
}

const body = fragments
  .map(([id, text]) => `  ${JSON.stringify(id)}: ${JSON.stringify(text)},`)
  .join('\n');

const generated = `// GENERATED by scripts/build-prompts.mjs — do not edit.
// Edit the markdown under src/prompts/ instead; this file is rebuilt by \`npm run build\`
// and is git-ignored so prompt diffs stay readable.

/** Every prompt fragment, inlined so the server survives being bundled. */
export const FRAGMENTS: Readonly<Record<string, string>> = Object.freeze({
${body}
});

export type FragmentId = keyof typeof FRAGMENTS;
`;

const previous = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : null;
if (previous !== generated) {
  fs.writeFileSync(outFile, generated, 'utf8');
  // Rewriting unchanged content would bump the mtime and make the protocol
  // suite's staleness guard think src/ moved ahead of build/ on every run.
  console.error(`[prompts] ${fragments.length} fragments → src/prompts/generated.ts`);
} else {
  console.error(`[prompts] ${fragments.length} fragments, unchanged`);
}
